{% set name = "opentsne" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2aecaa7a487100246f2d3fef9855d1bd6cc02a1c6da8fb2a54583f307aa4229
  patches:
    - patches/0001-fixed-test_neighbors-import.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cython
    - numpy {{ numpy }}
    - fftw 3.3.9
  run:
    - python
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]
    - {{ pin_compatible('numpy') }}
    - scikit-learn >=0.20
    - scipy
  run_constrained:
    - hnswlib >=0.4.0,<0.5.0
    - pynndescent >=0.5.0,<0.6.0

test:
  source_files:
    - tests
  imports:
    - openTSNE
  commands:
    - pip check
    - pytest -vv tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pavlin-policar/openTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible, parallel implementations of t-SNE
  description: |
    openTSNE is a modular Python implementation of t-Distributed Stochasitc Neighbor Embedding (t-SNE), a popular dimensionality-reduction algorithm for visualizing high-dimensional data sets.
  doc_url: https://opentsne.readthedocs.io
  dev_url: https://github.com/pavlin-policar/openTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
