{% set name = "openTSNE" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51f4dffaa3366ee4a480dd21d5f64eb0fa677248a0c99490aeb8bf311124368c

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv . --no-build-isolation
  skip: true  # [py<35 or s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cython
    - {{ pin_compatible('numpy') }}
    - fftw 3.3.9
  run:
    - python
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]
    - fftw >=3
    - numpy {{ numpy }}
    - scikit-learn >=0.20
    - scipy
    - pynndescent >=0.5.0,<0.6.0

test:
  imports:
    - openTSNE
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pavlin-policar/openTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible, parallel implementations of t-SNE
  doc_url: https://opentsne.readthedocs.io
  dev_url: https://github.com/pavlin-policar/openTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
